# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodbyeCorona' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodbyeCorona

pod 'Alamofire'
pod 'Charts'
  target 'GoodbyeCoronaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoodbyeCoronaUITests' do
    # Pods for testing
  end

end
